namespace: jjo93sa
name: day_one_ops
version: 0.0.1
readme: README.md
authors:
  - "James Osborne <dr.j.osborne@gmail.com>"
description: Roles and playbooks for performing initial system configuration
license_file: "LICENSE"
tags: []
dependencies: {}
repository: "https://github.com/jjo93sa/ansible-collection-day-one-ops.git"
