---
- name: Determine if Homebrew is already installed.
  ansible.builtin.command: command -v brew > /dev/null 2>&1
  register: brew_installed
  no_log: true
  ignore_errors: true
  changed_when: false

- name: Get the installation script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
    dest: "/tmp/install.sh"
    mode: "0777"
  when: brew_installed.rc != 0
  register: download_brew

- name: Run the Homebrew install script
  ansible.builtin.shell:
    cmd: /tmp/install.sh
  environment:
    NONINTERACTIVE: "1"
  when: download_brew.changed

- name: Clean-up the install script
  ansible.builtin.file:
    path: /tmp/install.sh
    state: absent

- name: Install and configure brew-file
  block:
    - name: Install brew-file as an easy way to manage installs
      ansible.builtin.command: brew install rcmdnk/file/brew-file

    - name: Configure user's shell
      ansible.builtin.include_tasks:
        file: "{{ deploy_user_shell }}.yml"

#TODO: Determine if ansible_user is correct
- name: Now install user requested packages
  block:
    - name: Template Brewfile
      ansible.builtin.template:
        src: Brewfile.j2
        dest: .config/brewfile/Brewfile
        mode: "0644"
        owner: ansible_user
        group: ansible_user

    - name: Now install the applications
      ansible.builtin.shell:
        cmd: brew file install --appstore 0
      environment:
        HOMEBREW_BREWFILE: ".config/brewfile/Brewfile"
