---
- name: Get users properties
  ansible.builtin.getent:
    database: passwd
    key: "{{ day_one_ops_deploy_user }}"
    split: ":"
  changed_when: false

- name: Set fact with user's shell
  ansible.builtin.set_fact:
    _deploy_user_shell: "{{ ansible_facts.getent_passwd[day_one_ops_deploy_user][5] | basename }}"
    _deploy_user_home: "{{ ansible_facts.getent_passwd[day_one_ops_deploy_user][4] }}"
