---
- name: Configure user shell
  ansible.builtin.blockinfile:
    path: "{{ _deploy_user_home }}/.zprofile"
    marker: "# {mark} Ansible managed - homebrew"
    block: |
      eval "$({{ _default_brew_path }}/brew shellenv)"
  become: true
  become_user: "{{ day_one_ops_deploy_user }}"

- name: Add wrapper
  ansible.builtin.blockinfile:
    path: "{{ _deploy_user_home }}/.zshrc"
    marker: "# {mark} Ansible managed - brewfile"
    block: |
      if [ -f $(brew --prefix)/etc/brew-wrap ];then
        source $(brew --prefix)/etc/brew-wrap
      fi
  become: true
  become_user: "{{ day_one_ops_deploy_user }}"
